version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_DATABASE: itonics
    env_file:
      - .env
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: itonics
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_DATABASE: itonics
      WEBZ_API_KEY: 3eb4d06f-315a-4481-b357-616444fc4e73
    env_file:
      - .env
    command: sh -c "npm run build && node dist/index.js"

volumes:
  pgdata:

